config/routes.rb
Rails.application.routes.draw do

  resources :wishlists do
    resources :items
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'static_pages/home'
  root 'static_pages#home'
  
  resources :parties do
    resources :invitations
    get '/send_reminder/:id' => "invitations#send_reminder", as: :send_reminder
  end

  get "/contacts/:importer/callback" => "invitations#callback"

  get "/contacts/failure" => "invitations#failure"

  get '/draw_names/:id' => "parties#draw_names", as: :draw_names
  get '/send_invitations/:id' => "parties#send_invitations", as: :send_invitations


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/party.rb
class Party < ApplicationRecord
  belongs_to :organizer, class_name: 'User'
  has_one :location
  has_many :invitations
  validates :spending_limit, numericality: {greater_than_or_equal_to: 0.01}

  accepts_nested_attributes_for :location

  after_create :add_invitation_to_organizer


  def add_invitation_to_organizer
    self.invitations.create(user_id: self.organizer.id)
  end

  def draw_names
    pool = invitations
    random_pool = pool.shuffle
    second_to_last = pool.length - 2
    random_pool[pool.length-1].receipient = random_pool[0].user
    random_pool[pool.length-1].save
    for i in 0..second_to_last
      random_pool[i].receipient = random_pool[i+1].user
      random_pool[i].save
    end
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :set_party, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :organizer?, only: [:show, :edit, :update, :destroy]

  # GET /parties
  # GET /parties.json
  def index
    @parties = Party.where(organizer_id: current_user.id)
    @invitations = current_user.invitations
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
    @invitation = Invitation.new(:party => @party)
  end

  # GET /parties/new
  def new
    @party = Party.new
  end

  # GET /parties/1/edit
  def edit
  end

  # POST /parties
  # POST /parties.json
  def create
    @user = current_user
    @party = @user.parties.create(party_params)

    respond_to do |format|
      if @party.save
        @party.create_location(location_params[:location_attributes])
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render :show, status: :created, location: @party }
      else
        format.html { render :new }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parties/1
  # PATCH/PUT /parties/1.json
  def update
    respond_to do |format|
      if @party.update(party_params)
        @party.location.update_attributes(location_params[:location_attributes])
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { render :show, status: :ok, location: @party }
      else
        format.html { render :edit }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party.destroy
    respond_to do |format|
      format.html { redirect_to parties_url, notice: 'Party was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def draw_names
    @party = Party.find(params[:id])
    @party.draw_names

    redirect_to @party, notice: 'Names Drawn Successfully.'
  end

  def send_invitations
    @party = Party.find(params[:id])
    @party.invitations.each do |invite|
      invite.send_invitation
    end
    redirect_to @party, notice: 'Invitations Successfully Sent!'
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def party_params
      params.require(:party).permit(:theme, :date, :time, :rsvp_deadline, :address, :spending_limit)
    end

    def location_params
      params.require(:party).permit(:location_attributes =>[:address, :latitude, :longitude])
    end

    def organizer?
      @party = Party.find(params[:id])
      if @party.organizer != current_user
        redirect_to root_url, notice: "You are not the party organizer"
      end
    end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_form.html.erb
<div class="container">


  <%= form_for(party) do |f| %>
    <% if party.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(party.errors.count, "error") %> prohibited this party from being saved:</h2>

        <ul>
        <% party.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :theme %>
      <%= f.text_field :theme %>
    </div>

    <div class="field">
      <%= f.label :spending_limit %>
      <%= f.text_field :spending_limit %>
    </div>

    <div class="field">
      <%= f.label :date %><br>
      <%= f.date_field :date, class: "datepicker" %>
    </div>

    <div class="field">
      <%= f.label :time %>
      <%= f.time_field :time, class:"timepicker" %>
    </div>

    <div class="field">
      <%= f.label :rsvp_deadline %>
      <%= f.date_field :rsvp_deadline, class: "datepicker" %>
    </div>

    <div class="field">
      <%= f.fields_for :location_attributes do |ff| %>
        <%= ff.label :address %>
        <%= ff.text_field :address ,  placeholder: "enter party location" %>
      <% end %>
    </div>

    <div class="actions">
      <%= f.submit class:'btn btn-small btn-primary' %>
    </div>
  <% end %>
</div>

app/views/parties/edit.html.erb
<h1>Editing Party</h1>

<%= render 'form', party: @party %>
<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<!-- ALL parties --> <!-- ALL parties --> <!-- ALL parties --> <!-- ALL parties --> <!-- ALL parties --> <!-- ALL parties --> <!-- ALL parties --> <!-- ALL parties --> <!-- ALL parties --> <!-- ALL parties --> <!-- ALL parties -->

<div class="imageBannerParties">
  <div>
    <p class="parties_banner">My Parties</p>
  </div>
</div>

<div class="row rowDatepicker">
  <div class="col s8 offset-s2 m6 offset-m3 l4 offset-l4">
    <input type="date" class="datepicker">
  </div>
</div>

          <div class="row partyList">
            <% @parties.each do |party| %>
            <div class="col s10 offset-s1 m3">
              <div class="card">
                <div class="card-image waves-effect waves-block waves-light">
                  <%=image_tag("reindeer.jpg", class:"activator")%>
                </div>
                <div class="card-content">
                    <span class="card-title activator grey-text text-darken-4"><%= party.theme %>
                    <i class="material-icons right">more_vert</i>
                    </span>
                  <p><%= link_to 'Show', party %></p>
                </div>
                <div class="card-reveal">
                  <span class="card-title grey-text text-darken-4"><%= party.theme %><i class="material-icons right">close</i></span>
                  <p><%= party.date %> - <%= party.time %></p>
                  <p><%= party.location.address unless party.location.nil? %></p>
                </div>
              </div>
              </div>
            <% end %>

          </div><!-- row -->

<h1>Parties I'm Organizing</h1>

<table>
  <thead>
    <tr>
      <th>Theme</th>
      <th>Date</th>
      <th>Time</th>
      <th>Rsvp deadline</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parties.each do |party| %>
      <tr>
        <td><%= party.theme %></td>
        <td><%= party.date %></td>
        <td><%= party.time %></td>
        <td><%= party.rsvp_deadline %></td>
        <td><%= party.location.address unless party.location.nil? %></td>
        <td><%= link_to 'Show', party %></td>
        <td><%= link_to 'Edit', edit_party_path(party) %></td>
        <td><%= link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h1>My Invitations</h1>

<table>
  <thead>
    <tr>
      <th>Theme</th>
      <th>Date</th>
      <th>Time</th>
      <th>Rsvp deadline</th>
      <th>Rsvp status</th>
      <th>Address</th>
      <th>Gift Receipient</th>
      <th>View Party Details</th>
    </tr>
  </thead>

  <tbody>
    <% @invitations.each do |invite| %>
      <tr>
        <td><%= invite.party.theme %></td>
        <td><%= invite.party.date %></td>
        <td><%= invite.party.time %></td>
        <td><%= invite.party.rsvp_deadline %></td>
        <% if invite.rsvp %>
          <td>Attending</td>
        <% else %>
          <% if invite.rsvp.nil? %>
            <td><%=link_to "Will Attend",
                       party_invitation_path(invite.party, invite,
                       :invitation => { :rsvp => true }),
                       :method=> :put ,
                       class:'btn btn-small btn-primary'%>
             <%=link_to "Will Not Attend",
                        party_invitation_path(invite.party, invite,
                        :invitation => { :rsvp => false }),
                        :method=> :put ,
                        class:'btn btn-small btn-primary'%></td>
          <% else %>

            <td>
              Not attending - Changed your mind? <%=link_to "Will Attend",
                       party_invitation_path(invite.party, invite,
                       :invitation => { :rsvp => true }),
                       :method=> :put ,
                       class:'btn btn-small btn-primary'%>
          <% end %>
        <% end %>
        <td><%= invite.party.location.address unless invite.party.location.nil? %></td>
        <td><%= invite.receipient.email unless invite.receipient.nil? %></td>
        <td><%= link_to 'Show', party_invitation_path(invite.party, invite) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/parties/new.html.erb
<h1>New Party</h1>

<%= render 'form', party: @party %>

<%= link_to 'Back', parties_path %>

app/views/parties/show.html.erb
<p>
  <strong>Theme:</strong>
  <%= @party.theme %>
</p>

<p>
  <strong>Date:</strong>
  <%= @party.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @party.time %>
</p>

<p>
  <strong>Rsvp deadline:</strong>
  <%= @party.rsvp_deadline %>
</p>

<p>
  <strong>Guest List | <%= link_to pluralize(@party.invitations.size, 'Guest'), party_invitations_path(@party) %> | <%= link_to 'Draw Names', draw_names_path(@party) %> | <%= link_to 'Send Invitations', send_invitations_path %> </strong>
  <table>
    <thead>
      <tr>
        <th>Email</th>
        <th>Rsvp Status</th>
        <th>Gift receipient</th>
        <th>Remove From Guest List</th>
      </tr>
    </thead>

    <tbody>
      <% @party.invitations.each do |invite| %>
        <tr>
          <td><%= invite.user.email %></td>
          <td><%= invite.rsvp_status %></td>
          <td><%= invite.receipient.email unless invite.receipient.nil? %></td>
          <td><%= link_to 'See invite', party_invitation_path(@party, invite) %></td>
          <td><%= link_to 'Send Reminder', party_send_reminder_path(@party, invite) %></td>
          <td><%= link_to 'Remove from Guest List', [@party, invite], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>


</p>
<% if @party.location != nil %>
<p>
  <strong>Address:</strong>
  <%= @party.location.address %>


<%= content_tag :div, class: "lat_information", data: {lat: @party.location.latitude, lng: @party.location.longitude} do %>
<% end %>

 <div id="map" style="height: 500px; width: 500px; margin: auto;"></div>
<% end %>

<p><%= link_to "Add Invitees", new_party_invitation_path(@party) %> | <% link = "/contacts/gmail/" %>
<a href=<%=link %>>Import Invitees from Gmail</a></p>



<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>



<script type="text/javascript">
// Google Maps Scripts
// When the window has finished loading create our google map below
$(document).ready(function(){

    // longitude and latitude variables:
    var lat = $('.lat_information').data('lat')
    var lng = $('.lat_information').data('lng')
    // Basic options for a simple Google Map
    // For more options see: https://developers.google.com/maps/documentation/javascript/reference#MapOptions
    var mapOptions = {
        // How zoomed in you want the map to start at (always required)
        zoom: 15,
        // The latitude and longitude to center the map (always required)
        center: new google.maps.LatLng(lat, lng),
        // Disables the default Google Maps UI components
        disableDefaultUI: true,
        scrollwheel: false,
        draggable: false,
        // How you would like to style the map.
        // This is where you would paste any style found on Snazzy Maps.
        styles: [{
            "featureType": "water",
            "elementType": "geometry",
            "stylers": [{
                "color": "#000000"
            }, {
                "lightness": 17
            }]
        }, {
            "featureType": "landscape",
            "elementType": "geometry",
            "stylers": [{
                "color": "#000000"
            }, {
                "lightness": 20
            }]
        }, {
            "featureType": "road.highway",
            "elementType": "geometry.fill",
            "stylers": [{
                "color": "#000000"
            }, {
                "lightness": 17
            }]
        }, {
            "featureType": "road.highway",
            "elementType": "geometry.stroke",
            "stylers": [{
                "color": "#000000"
            }, {
                "lightness": 29
            }, {
                "weight": 0.2
            }]
        }, {
            "featureType": "road.arterial",
            "elementType": "geometry",
            "stylers": [{
                "color": "#000000"
            }, {
                "lightness": 18
            }]
        }, {
            "featureType": "road.local",
            "elementType": "geometry",
            "stylers": [{
                "color": "#000000"
            }, {
                "lightness": 16
            }]
        }, {
            "featureType": "poi",
            "elementType": "geometry",
            "stylers": [{
                "color": "#000000"
            }, {
                "lightness": 21
            }]
        }, {
            "elementType": "labels.text.stroke",
            "stylers": [{
                "visibility": "on"
            }, {
                "color": "#000000"
            }, {
                "lightness": 16
            }]
        }, {
            "elementType": "labels.text.fill",
            "stylers": [{
                "saturation": 36
            }, {
                "color": "#000000"
            }, {
                "lightness": 40
            }]
        }, {
            "elementType": "labels.icon",
            "stylers": [{
                "visibility": "off"
            }]
        }, {
            "featureType": "transit",
            "elementType": "geometry",
            "stylers": [{
                "color": "#000000"
            }, {
                "lightness": 19
            }]
        }, {
            "featureType": "administrative",
            "elementType": "geometry.fill",
            "stylers": [{
                "color": "#000000"
            }, {
                "lightness": 20
            }]
        }, {
            "featureType": "administrative",
            "elementType": "geometry.stroke",
            "stylers": [{
                "color": "#000000"
            }, {
                "lightness": 17
            }, {
                "weight": 1.2
            }]
        }]
    };
    // Get the HTML DOM element that will contain your map
    // We are using a div with id="map" seen below in the <body>
    var mapElement = document.getElementById('map');
    // Create the Google Map using out element and options defined above
    var map = new google.maps.Map(mapElement, mapOptions);
    // Custom Map Marker Icon - Customize the map-marker.png file to customize your icon
  //  var image = '/images/map-marker.png';
    var myLatLng = new google.maps.LatLng(lat,lng);
    var beachMarker = new google.maps.Marker({
        position: myLatLng,
        map: map //,
      //  icon: image
    });
});
</script>