config/routes.rb
Rails.application.routes.draw do

  resources :wishlists do
    resources :items
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'static_pages/home'
  root 'static_pages#home'
  
  resources :parties do
    resources :invitations
    get '/send_reminder/:id' => "invitations#send_reminder", as: :send_reminder
  end

  get "/contacts/:importer/callback" => "invitations#callback"

  get "/contacts/failure" => "invitations#failure"

  get '/draw_names/:id' => "parties#draw_names", as: :draw_names
  get '/send_invitations/:id' => "parties#send_invitations", as: :send_invitations


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :wishlist

  def amazon?
    self.url != nil && self.url.include?("amazon")
  end

  def asin
    if self.amazon?
      page = MetaInspector.new(url)
      parsed_page = page.parsed
      long_list = parsed_page.css("li span.a-list-item").text
      return long_list.slice(long_list.index("ASIN:")+47,10)
    end
  end

  def iframe_url
    if self.amazon?
      iframe_url = "//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=thenewoutpro-20&marketplace=amazon&region=US&placement="+self.asin+"&asins="+self.asin+"&show_border=false&link_opens_in_new_window=true&price_color=333333&title_color=819bb3&bg_color=ffffff"

    end
  end

  def get_price
    if !self.amazon?
      page = MetaInspector.new(url)
      parsed_page = page.parsed
      long_list = parsed_page.css("h5.product-price").text
      return long_list.slice(long_list.index("$"),7)
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @wishlist = Wishlist.find(params[:wishlist_id])
    url = @item.url

    @page =  MetaInspector.new(url)
    if @item.amazon?
      @asin = @item.asin
      @iframe_url = @item.iframe_url
    else
      @price = @item.get_price
    end
  end

  # GET /items/new
  def new
    @wishlist = Wishlist.find(params[:wishlist_id])
    @item = @wishlist.items.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @wishlist = Wishlist.find(params[:wishlist_id])
    @item = @wishlist.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @wishlist, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :url, :price)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for [@wishlist, @item] do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit 'Add Item' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.url %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render :partial => 'form' %>

<%= link_to 'Back', wishlist_path(@wishlist) %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>



<% if @item.amazon? %>
<iframe style="width:120px;height:240px;"
marginwidth="0" marginheight="0" scrolling="no" frameborder="0"
src=<%=@item.iframe_url%>>
</iframe>
<% else %>


<p>
  <strong>Name:</strong>
  <%=link_to @page.title, @item.url %>
  <%= image_tag(@page.images.best, :alt => @page.description) %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<%= link_to 'Edit', edit_wishlist_item_path(@item) %> |
<%= link_to 'Back', wishlist_path(@wishlist) %>
<% end %>