config/routes.rb
Rails.application.routes.draw do

  resources :wishlists do
    resources :items
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'static_pages/home'
  root 'static_pages#home'
  
  resources :parties do
    resources :invitations
    get '/send_reminder/:id' => "invitations#send_reminder", as: :send_reminder
  end

  get "/contacts/:importer/callback" => "invitations#callback"

  get "/contacts/failure" => "invitations#failure"

  get '/draw_names/:id' => "parties#draw_names", as: :draw_names
  get '/send_invitations/:id' => "parties#send_invitations", as: :send_invitations


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  has_many :items
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :set_wishlist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /wishlists
  # GET /wishlists.json
  def index
    @wishlists = Wishlist.all
  end

  # GET /wishlists/1
  # GET /wishlists/1.json
  def show
  end

  # GET /wishlists/new
  def new

    @wishlist = current_user.wishlists.build
  end

  # GET /wishlists/1/edit
  def edit
  end

  # POST /wishlists
  # POST /wishlists.json
  def create
    @wishlist = current_user.wishlists.create(wishlist_params)

    respond_to do |format|
      if @wishlist.save
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully created.' }
        format.json { render :show, status: :created, location: @wishlist }
      else
        format.html { render :new }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishlists/1
  # PATCH/PUT /wishlists/1.json
  def update
    respond_to do |format|
      if @wishlist.update(wishlist_params)
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @wishlist }
      else
        format.html { render :edit }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishlists/1
  # DELETE /wishlists/1.json
  def destroy
    @wishlist.destroy
    respond_to do |format|
      format.html { redirect_to wishlists_url, notice: 'Wishlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wishlist
      @wishlist = Wishlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wishlist_params
      params.require(:wishlist).permit(:title, :user_id)
    end
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_form.html.erb
<%= form_for(wishlist) do |f| %>
  <% if wishlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wishlist.errors.count, "error") %> prohibited this wishlist from being saved:</h2>

      <ul>
      <% wishlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishlists/edit.html.erb
<h1>Editing Wishlist</h1>

<%= render 'form', wishlist: @wishlist %>

<%= link_to 'Show', @wishlist %> |
<%= link_to 'Back', wishlists_path %>

app/views/wishlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wishlists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wishlists.each do |wishlist| %>
      <tr>
        <td><%= wishlist.title %></td>
        <td><%= wishlist.user %></td>
        <td><%= link_to 'Show', wishlist %></td>
        <td><%= link_to 'Edit', edit_wishlist_path(wishlist) %></td>
        <td><%= link_to 'Destroy', wishlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wishlist', new_wishlist_path %>

app/views/wishlists/new.html.erb
<h1>New Wishlist</h1>

<%= render 'form', wishlist: @wishlist %>

<%= link_to 'Back', wishlists_path %>

app/views/wishlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @wishlist.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @wishlist.user %>
</p>

<%= link_to 'Edit', edit_wishlist_path(@wishlist) %> |
<% if @wishlist.items == [] %>
<%= link_to 'Add Items to Your Wishlist', new_wishlist_item_path(@wishlist) %> |
<% else %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @wishlist.items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Show', wishlist_item_path(@wishlist,item) %></td>
        <td><%= link_to 'Shop', item.url %></td>
        <td><%= link_to 'Edit', edit_wishlist_item_path(item) %></td>
        <td><%= link_to 'Destroy', wishlist_item_path(item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Add More Items', new_wishlist_item_path(@wishlist) %> |
<% end %>
<%= link_to 'Back', wishlists_path %>