config/routes.rb
Rails.application.routes.draw do

  resources :wishlists do
    resources :items
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'static_pages/home'
  root 'static_pages#home'
  
  resources :parties do
    resources :invitations
    get '/send_reminder/:id' => "invitations#send_reminder", as: :send_reminder
  end

  get "/contacts/:importer/callback" => "invitations#callback"

  get "/contacts/failure" => "invitations#failure"

  get '/draw_names/:id' => "parties#draw_names", as: :draw_names
  get '/send_invitations/:id' => "parties#send_invitations", as: :send_invitations


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_signed_in_nav.html.erb
<li><%= link_to 'Parties', parties_path %></li>
<li><%= link_to 'Add New Party', new_party_path %></li>
<li><%= link_to 'Wishlists', wishlists_path %></li>
<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>

app/views/layouts/_signed_out_nav.html.erb
<li><%= link_to 'Login', new_user_session_path %></li>
<li><a href="#signupForm">SignUp</a></li>
<li><a href="#aboutUsSection">About</a></li>
<li><a href="#">Contact</a></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecretSanta</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>

<!-- NAVIGATION --><!-- NAVIGATION --><!-- NAVIGATION --><!-- NAVIGATION --><!-- NAVIGATION --><!-- NAVIGATION --><!-- NAVIGATION --><!-- NAVIGATION -->

  <nav class="mainNav #43a047 green darken-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">... SecretSanta ...</a>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <% if user_signed_in? %>
          <%= render 'layouts/signed_in_nav' %>
        <% else %>
          <%= render 'layouts/signed_out_nav' %>
        <% end %>

      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><%= link_to 'Login', new_user_session_path %></li>
        <li><a href="#signupForm">SignUp</a></li>
        <li><a href="#aboutUsSection">About</a></li>
        <li><a href="#">Contact</a></li>
      </ul>

    </div> <!-- class="nav-wrapper container" -->
  </nav>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       <%= yield %>

<!-- FOOTER --><!-- FOOTER --><!-- FOOTER --><!-- FOOTER --><!-- FOOTER --><!-- FOOTER --><!-- FOOTER --><!-- FOOTER --><!-- FOOTER --><!-- FOOTER --><!-- FOOTER -->

     <footer class="page-footer #f44336 red">
       <div class="container">
         <div class="row">
           <div class="col l1 s12">
             <h6><a href="#">Login</a></h6>
           </div>
           <div class="col l1 s12">
             <h6><a href="#signupForm">SignUp</a></h6>
           </div>
           <div class="col l1 s12">
             <h6><a href="#aboutUsSection">About</a></h6>
           </div>
           <div class="col l1 s12">
             <h6><a href="#">Contact</a></h6>
           </div>
         </div>
       </div>
     </footer>
  </body>
  <!-- Scripts -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA5xQYBkfGUCndDrVrcUEgMw6ldd5puQ_0&services=geocoding&libraries=places,visualization">
  </script>


</html>